### ISSUE TITLE
Add hash methods to the base classes

### ISSUE THREAD

**Issue by mxkmp** [spotify-web-api-java/spotify-web-api-java#262]
To use Hashmaps and Hashsets it would be nice to add  the hash method to every base class.

**Comment by dargmuesli** [comment]
PRs welcome!

**Comment by it5-j05h** [comment]
[](https://www.geeksforgeeks.org/hashmap-treemap-java/)  this could be somewhere to start.

**Comment by ezienecker** [comment]
@dargmuesli please check my PR: https://github.com/spotify-web-api-java/spotify-web-api-java/pull/307

**Comment by dargmuesli** [comment]
Aren't hash methods to be added to every class in `model_objects`? @mxkmp, cc @ezienecker

**Comment by ezienecker** [comment]
I have added others that make sense from my perspective.

**Comment by dargmuesli** [comment]
Thank you, @ezienecker!
