### ISSUE TITLE
Control multiple Users with one Client ID

### ISSUE THREAD

**Issue by Jilence** [spotify-web-api-java/spotify-web-api-java#264]
Hello!

I have following problem. So, I created a Spotify-Application, for the client_id and the client_secret. Then I created a link, that return the auth code. With this code, I create the access token and refresh token. 
Now I want to control the Spotify Account, from the User, how clicked on the linked, with my client_id.
**BUT**, when I click on the link, its working, but when my friends click on the link, it didnt work. 

So is this my fault?

**Comment by dargmuesli** [comment]
Hello, please respect the issue template.
