### ISSUE TITLE
User.getEmail returning null

### ISSUE THREAD

**Issue by TerrizX** [spotify-web-api-java/spotify-web-api-java#267]
Same with CountryCode too and getBirthdate. Whenever I call them they return null.

**Comment by dargmuesli** [comment]
I guess you're trying to get a user's data but not the current user's data. But without a code example it won't be possible to do more than guessing. We can surely reopen this issue once a valid reproduction is given.

https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-profile
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-current-users-profile

**Comment by TerrizX** [comment]
Sorry, I used the PCKE method for authorization and just used the Get Current User profile example that's already on here, all I did was change user.displayName to user.getEmail and getCountryCode. But everytime I did and ran it, it displays null. I haven't added any custom code besides changing the user.get

**Comment by dargmuesli** [comment]
Thanks for providing details that allow me to help. I'll get back to you when I had time to investigate.

**Comment by dargmuesli** [comment]
Did you set appropriate scopes? https://github.com/spotify-web-api-java/spotify-web-api-java/blob/d3dfa254aac3082e1ad055c629ebf88ccfb414f2/examples/authorization/authorization_code/pkce/AuthorizationCodePKCEUriExample.java#L23
`user-read-private,user-read-email` should be valid: https://developer.spotify.com/documentation/general/guides/authorization/scopes/
`user-read-birthdate` seems outdated.

**Comment by TerrizX** [comment]
Nah I didn't, thanks for the help. Thought they were commented out because they were deprecated.
