### ISSUE TITLE
AuthorizationCodePKCERefreshRequest returns a BadRequestException.

### ISSUE THREAD

**Issue by nil-malh** [spotify-web-api-java/spotify-web-api-java#270]
Hello there,

When trying to refresh my access token via the AuthorizationCodePKCERefreshRequest.class it returns a bad request exception : 

```

se.michaelthelin.spotify.exceptions.detailed.BadRequestException: 
	at se.michaelthelin.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:320)
	at se.michaelthelin.spotify.SpotifyHttpManager.post(SpotifyHttpManager.java:183)
	at se.michaelthelin.spotify.requests.AbstractRequest.postJson(AbstractRequest.java:121)
	at se.michaelthelin.spotify.requests.authorization.authorization_code.pkce.AuthorizationCodePKCERefreshRequest.execute(AuthorizationCodePKCERefreshRequest.java:36)
	at fr.nil.spotimine.Try.main(Try.java:56)

```
Any idea on what to do to fix that issue ?
Best regards.

**Comment by dargmuesli** [comment]
Try inspecting the actual error message or give the code you use for that request so that I'm able to assist.

**Comment by nil-malh** [comment]
Hello there, here is the code used to refresh my token (it came from the repo's example : 

``public class RefreshToken {

private static SpotifyApi spotifyApi = Core.spotifyApi;

    private static final AuthorizationCodePKCERefreshRequest authorizationCodePKCERefreshRequest = spotifyApi.authorizationCodePKCERefresh()
            .build();


    public static Runnable runnable = new Runnable() {
        @Override
        public void run() {
            System.out.println("Refresh token =" + Core.refreshToken);
            authorizationCodeRefresh_Async();
        }

        public static void main(String[] args) {
            System.out.println("hi");
            ScheduledThreadPoolExecutor exec = new ScheduledThreadPoolExecutor(1);
                    exec.scheduleAtFixedRate(runnable,0,1, TimeUnit.SECONDS);
        }
    };

    public static void authorizationCodeRefresh_Async() {
        try {
            final CompletableFuture<AuthorizationCodeCredentials> authorizationCodeCredentialsFuture = authorizationCodePKCERefreshRequest.executeAsync();

            // Thread free to do other tasks...
            // Example Only. Never block in production code.
            final AuthorizationCodeCredentials authorizationCodeCredentials = authorizationCodeCredentialsFuture.join();
            // Set access token for further "spotifyApi" object usage
            spotifyApi.setAccessToken(authorizationCodeCredentials.getAccessToken());
            System.out.println(authorizationCodeCredentials.getAccessToken());
            System.out.println("Expires in: " + authorizationCodeCredentials.getExpiresIn());
        } catch (CompletionException e) {
            System.out.println("Error: " + e.getCause().getMessage());
        } catch (CancellationException e) {
            System.out.println("Async operation cancelled.");
        }
    }
}
``
