### ISSUE TITLE
Getting Forbidden error

### ISSUE THREAD

**Issue by abhi-jha** [spotify-web-api-java/spotify-web-api-java#279]
get top artists : https://github.com/spotify-web-api-java/spotify-web-api-java/blob/develop/examples/data/personalization/simplified/GetUsersTopArtistsExample.java

I have replaced my access token and it throws an error with Forbidden. Is there any way to set scope in the whole flow?

Spotify has scopes that can be set : https://developer.spotify.com/documentation/general/guides/authorization/scopes/#user-library-read

**Comment by dargmuesli** [comment]
Does https://github.com/spotify-web-api-java/spotify-web-api-java/discussions/276#discussioncomment-1965342 help?

**Comment by abhi-jha** [comment]
Where do I set it though?

**Comment by dargmuesli** [comment]
For the `AuthorizationCodeUriRequest` e.g. 
```Java
private static final AuthorizationCodeUriRequest authorizationCodeUriRequest = spotifyApi.authorizationCodeUri()
  .scope("user-top-read")
  .build();
```
