### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: se/michaelthelin/spotify/exceptions/SpotifyWebApiException

### ISSUE THREAD

**Issue by duongtuan303030** [spotify-web-api-java/spotify-web-api-java#287]
![image](https://user-images.githubusercontent.com/80153297/163219722-f69ef0ce-a740-4377-a7e6-d56514cf95db.png)
error when convert to jar

**Comment by dargmuesli** [comment]
Not sure what that `discord.jar` is. Please add more information and I'll happily reopen this issue if it turns out to be one related to this project.
