### ISSUE TITLE
Error: Unable to initialize main class Main Caused by: java.lang.NoClassDefFoundError: se/michaelthelin/spotify/exceptions/SpotifyWebApiException

### ISSUE THREAD

**Issue by duongtuan303030** [spotify-web-api-java/spotify-web-api-java#288]
![image](https://user-images.githubusercontent.com/80153297/163324484-61359185-4341-4a9b-a2c8-c37ae2e5f4e2.png)
![image](https://user-images.githubusercontent.com/80153297/163324675-ed9518b5-8e6b-4253-9158-c70e3e58d358.png)
error when convert to jar and run and work in gradlew 
```
Error: Unable to initialize main class Main
Caused by: java.lang.NoClassDefFoundError: se/michaelthelin/spotify/exceptions/SpotifyWebApiException
```
![image](https://user-images.githubusercontent.com/80153297/163324118-b7d78385-ec1a-4be9-b197-a46aa828e6d7.png)

**Comment by duongtuan303030** [comment]
build.gradle file
```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

compileJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
    maven {
        url 'https://m2.dv8tion.net/releases'
    }
}

dependencies {
    //Change 'implementation' to 'compile' in old Gradle versions
    implementation("net.dv8tion:JDA:5.0.0-alpha.9")
    implementation('com.sedmelluq:lavaplayer:1.3.75')
    implementation('se.michaelthelin.spotify:spotify-web-api-java:7.0.1')
}
```

**Comment by duongtuan303030** [comment]
fixed by update build

**Comment by dragonismcode** [comment]
I'm having this same issue and can't seem to figure out the problem.  I'm not sure what's wrong. Here is my pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>tech.dragonism</groupId>
    <artifactId>Spot</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Spot</name>

    <description>Shows information about the player's song information on Spotify</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <url>https://dragonism.tech</url>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>18</source>
                    <target>18</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.18.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>se.michaelthelin.spotify</groupId>
            <artifactId>spotify-web-api-java</artifactId>
            <version>7.1.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
`

**Comment by dragonismcode** [comment]
The exact error message I'm getting:
```
[18:17:53 ERROR]: Error occurred while enabling Spot v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: se/michaelthelin/spotify/exceptions/SpotifyWebApiException
```

I am running this on a Paper 1.18.2 server if that's any help.

**Comment by dragonismcode** [comment]
I'm sorry. I solved this problem in less than 5 minutes of posting this. I apologize for adding here but I'm just going to leave my solution here just in case someone else has the same issue.

I was telling Maven that the scope was provided

    <dependency>
        <groupId>se.michaelthelin.spotify</groupId>
        <artifactId>spotify-web-api-java</artifactId>
        <version>7.0.0</version>
        --> <scope>provided</scope> <--
    </dependency>

Don't add tell Maven the scope was already provided. Delete the line the arrows are pointing to above in case you have them
