### ISSUE TITLE
pls add getartists for IPlaylistItem (getPlaylistsItems)

### ISSUE THREAD

**Issue by duongtuan303030** [spotify-web-api-java/spotify-web-api-java#289]
why not add artists for getPlaylistsItems when api have it :\
check out : https://developer.spotify.com/console/get-playlist-tracks/

**Comment by dargmuesli** [comment]
Please do a little bit of research before you open another issue. This repo includes an example for what you're searching for: https://github.com/spotify-web-api-java/spotify-web-api-java/blob/develop/examples/data/playlists/GetPlaylistsItemsExample.java

**Comment by dargmuesli** [comment]
https://github.com/spotify-web-api-java/spotify-web-api-java/issues/216#issuecomment-640938068

**Comment by dargmuesli** [comment]
That would be a good opportunity for a training PR for anyone interested.
