### ISSUE TITLE
help clientCredentials.getExpiresIn() time fomad

### ISSUE THREAD

**Issue by duongtuan303030** [spotify-web-api-java/spotify-web-api-java#290]
https://github.com/spotify-web-api-java/spotify-web-api-java/blob/develop/examples/authorization/client_credentials/ClientCredentialsExample.java
*doc

**Comment by dargmuesli** [comment]
https://spotify-web-api-java.github.io/spotify-web-api-java/se/michaelthelin/spotify/model_objects/credentials/ClientCredentials.html#getExpiresIn()
Please do not open any other issue like this.

**Comment by duongtuan303030** [comment]
> https://spotify-web-api-java.github.io/spotify-web-api-java/se/michaelthelin/spotify/model_objects/credentials/ClientCredentials.html#getExpiresIn() Please do not open any other issue like this.

... i dont see that link in https://github.com/spotify-web-api-java/spotify-web-api-java#readme

**Comment by dargmuesli** [comment]
You can find it under the heading "[documentation](https://github.com/spotify-web-api-java/spotify-web-api-java#documentation)".

**Comment by duongtuan303030** [comment]
> You can find it under the heading "[documentation](https://github.com/spotify-web-api-java/spotify-web-api-java#documentation)".

thank
