### ISSUE TITLE
java.lang.NoSuchMethodError with GSON parseString

### ISSUE THREAD

**Issue by Sxmurai** [spotify-web-api-java/spotify-web-api-java#295]
I saw issue #224 and I tried the solution in there, and that did not work. I invalidated/restarted my IntelliJ cache, I tried to remove the GSON library I was using and used the one that the JAR downloaded when I put it into my build.gradle, nothing seems to have worked.

I am using v6.5.4 as that is the last version (that I'm aware of) that is compiled with Java 8.

Here is where the problem is:

```java
    AuthorizationCodePKCERequest authorizationCodePKCERequest = api.authorizationCodePKCE(code, VERIFIER).build();
    try {
      AuthorizationCodeCredentials credentials = authorizationCodePKCERequest.execute();
```

After I run `.execute()` it throws an exception:

```
Exception in thread "Thread-15" java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
	at com.wrapper.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:296)
	at com.wrapper.spotify.SpotifyHttpManager.post(SpotifyHttpManager.java:183)
	at com.wrapper.spotify.requests.AbstractRequest.postJson(AbstractRequest.java:123)
	at com.wrapper.spotify.requests.authorization.authorization_code.pkce.AuthorizationCodePKCERequest.execute(AuthorizationCodePKCERequest.java:37)
```

Which I find weird, because when opening it up in IntelliJ Ctrl + Click, it.. doesn't have any errors? And Ctrl + Clicking `parseString` brings me to the method it otherwise could not find?

![image](https://user-images.githubusercontent.com/57580886/167278271-19457cd5-357e-45d4-97fc-c8f1e5674e23.png)

The request works fine, as I did some testing before trying to get the authorization codes and the callback worked fine, and I was able to get the code + the window opens to authorize with my application.

Any pointers? I'm genuinely confused and I'm entirely lost.

Edit: Proof that I can get the code just fine:
![image](https://user-images.githubusercontent.com/57580886/167278458-c378ff3b-3d29-45e5-847f-111232fcdfb1.png)

**Comment by dargmuesli** [comment]
Heyhey, thank you for the detailed description!
One thing that you might try is to delete (/rename) the `.gradle` directories in your project's root and your user's OS account directory.

**Comment by Sxmurai** [comment]
Thanks for the response! I tried that and then re-synced my gradle project and unfortunately that did not solve it. I checked the .gradle directory and everything seemed alright. It even claims it has GSON 2.8.6 cached too.

![image](https://user-images.githubusercontent.com/57580886/167304110-2cbdc817-785f-44d9-ac1b-774fef6a4881.png)

Anything else you might suggest? Thanks!

**Comment by dargmuesli** [comment]
Could you please try downgrading to another minor version? Maybe start with the patch level first. Try `6.5.3` and then `6.4.1`.

Background: I think at some point there was an issue uploading the artifact to Maven so kind of a half baked module migration was pushed there incorrectly. By design it is not possible to remove uploaded artifacts afterwards, so that might have been `6.5.4` eventhough I can't see a culprit in the git history now.
If an older version works for you I could republish that version under a new `6`er version number. The last few patch or minor level changes were not very significant so downgrading should not make you loose essential features.

**Comment by Sxmurai** [comment]
I tried to install the following: 6.5.3, 6.4.1, 6.4.0, and 6.3.0. None of which solved the issue.

Should I try downgrading/upgrading my gradle version? To be fair, I am on an older version of gradle for sakes of an older build.gradle I made to work with what I'm doing.

**Comment by dargmuesli** [comment]
Hm, then I'm out of immediate ideas for now. Yes, you can try that!

**Comment by Sxmurai** [comment]
I tried what I suggested, and that did not work either.

I thank you for trying to help me though! I'll keep this issue open in case I find a fix, unless you'd like to close it.

**Comment by Sxmurai** [comment]
So update on this, I recently upgraded to Java 17 and it seems to work now, thanks for all of the help. It just seems like for some reason it didn't like java 8
