### ISSUE TITLE
`Device` does not wrap the `is_private_session` flag.

### ISSUE THREAD

**Issue by jdngray77** [spotify-web-api-java/spotify-web-api-java#300]
The API will withhold information about playback if the client is in a private session.

Typically you can check for this from the `device` object from the playback endpoint, but the wrapper does not have the flag.

Below are some refs showing the flag in the responses.

https://developer.spotify.com/documentation/web-api/reference/#/operations/get-information-about-the-users-current-playback
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-a-users-available-devices

**Comment by dargmuesli** [comment]
PR welcome!
