### ISSUE TITLE
AudioAnalysis.track.mode is always null

### ISSUE THREAD

**Issue by alexeynefdef** [spotify-web-api-java/spotify-web-api-java#302]
Hey there! I'm trying to build a simple app using your very cool lib, but there is a problem:

Return value of AudioAnalysis.track.mode is always null.
I've already tried to get it with java HTTP client and it works properly so i guess there is a small bug.
Best regards

**Comment by dargmuesli** [comment]
The fix should soon be available as `v7.2.1` :partying_face:
