### ISSUE TITLE
GetShowRequest: "non existing id"

### ISSUE THREAD

**Issue by KyllianGamer** [spotify-web-api-java/spotify-web-api-java#303]
When creating a GetShowRequest and executing it I get the following error: `se.michaelthelin.spotify.exceptions.detailed.NotFoundException: non existing id`

Even though I tried multiple IDs and they should be correct, example: "7FGIgWaSwBsAkKkjYf2oQV"

Doing the same thing but for playlists, tracks, artists etc. works fine.

**Comment by TheKnightKarim** [comment]
Same happening with GetAlbumsTracksRequest

**Comment by dargmuesli** [comment]
I cannot reproduce that behavior. Please try again and if the issue persists, post the code you use and the id you put in.

**Comment by TheKnightKarim** [comment]
```java
Arrays.asList(spotifyApi.getListOfCurrentUsersPlaylists().build().execute().getItems()).forEach(playlist -> {
            GetAlbumsTracksRequest getAlbumsTracksRequest = spotifyApi.getAlbumsTracks(playlist.getId()).build();
            final Paging<TrackSimplified> trackSimplifiedPaging;
            try {
                trackSimplifiedPaging = getAlbumsTracksRequest.execute();
            } catch (IOException | SpotifyWebApiException | ParseException e) {
                throw new RuntimeException(e);
            }
        });
```

**Comment by dargmuesli** [comment]
Make sure to use an actual show id, not an episode id. Or an album id, not a playlist id.
