### ISSUE TITLE
fix: docs throw 404

### ISSUE THREAD

**Issue by Minecon724** [spotify-web-api-java/spotify-web-api-java#312]
trying to search returns a 404
which is definitely not what i was looking for

**Comment by dargmuesli** [comment]
I faced this issue once too, but cannot reproduce it right now. Do you have a specific search query that causes this behavior?

**Comment by Minecon724** [comment]
> I faced this issue once too, but cannot reproduce it right now. Do you have a specific search query that causes this behavior?

click on any class

**Comment by Minecon724** [comment]
theres a random "undefined" inserted into the url

**Comment by dargmuesli** [comment]
Should be fixed now with a98b2952d0d85b9b6b2ddd5d3c8555a7e7815abc :)
