### ISSUE TITLE
/me/tracks needs ids in body not querystring

### ISSUE THREAD

**Issue by constructivetim** [spotify-web-api-java/spotify-web-api-java#317]
this api no longer works with Ids placed in the body (returns Bad request), rather is must have ids on the query string

https://developer.spotify.com/documentation/web-api/reference/#/operations/save-tracks-user

I think spotify broke something earlier this week, but the docs say that the query string ids parameter is _required_

**Comment by dargmuesli** [comment]
Thank you for the report.
I just tried both methods as given in [the example](https://github.com/spotify-web-api-java/spotify-web-api-java/blob/725eafb393877d73927ffd386ce136031030eda7/examples/data/library/SaveTracksForUserExample.java) and both still worked. Please provide a full code example that reproduces the issue and I'll reopen this ticket! :pray:
