### ISSUE TITLE
getTheUsersQueue is incomplete

### ISSUE THREAD

**Issue by Selbi182** [spotify-web-api-java/spotify-web-api-java#328]
The new "getTheUsersQueue" method has two issues in its current form:

1. The "currentyPlaying" part is completely ignored.
2. The method casts anything it returns to Track, rather than taking a case-by-case approach. As a result, if any podcasts are in the queue, they get erronously casted to Track, which doesn't cause any exceptions, but still results in attributes like the "Show" part being completely dropped.

**Comment by dargmuesli** [comment]
Hey Selbi, thank you for the report. Would you be up to help contribute a solution to the issues mentioned?

**Comment by Selbi182** [comment]
I was going to see if you wanted to tackle the issue yourself. But sure, I could take a look at it and submit a PR :)

**Comment by dargmuesli** [comment]
I'm currently not using this library much, but want to remain as one who takes time to react to input! :)

**Comment by Selbi182** [comment]
PR is ready: https://github.com/spotify-web-api-java/spotify-web-api-java/pull/329

**Comment by Selbi182** [comment]
Don't want to be pushy, I'm just curious when you think you'll get the merge done. I'm kind of waiting for the new version so I can use this feature 😅

**Comment by dargmuesli** [comment]
I'm currently moving. I think at latest will be on the weekend.

**Comment by Selbi182** [comment]
Gotcha, don't worry about it. Thanks for letting me know and good luck with your move! I'll be waiting 😊

**Comment by GreenRabbits** [comment]
I have got the same issue and I am also looking for a fix 😄

**Comment by dargmuesli** [comment]
Should be released in v8 shortly.

**Comment by Selbi182** [comment]
Thank you so much!
