### ISSUE TITLE
Http Client hangs when 429 is returned

### ISSUE THREAD

**Issue by SergioBarbero** [spotify-web-api-java/spotify-web-api-java#344]
When the API is overwhelmed with requests and starts returning 429, the call via library hangs. This seems an error related to the apache http client itself

**Comment by dargmuesli** [comment]
What exactly do you mean with "hangs"?

**Comment by SergioBarbero** [comment]
The method call freezes, blocking the thread forever

**Comment by dargmuesli** [comment]
I'm currently on vacation. If you could fine out the cause in the next 2-3 weeks while I'm away, I'd very much welcome a PR!

**Comment by SergioBarbero** [comment]
I'm trying to fix it. There's some issue with the http client. To reproduce it:

1. Make sure you receive a 429 error. Then:

    @Test
    public void getArtistReal() throws IOException, ParseException, SpotifyWebApiException {
        SpotifyApi spotifyApi = new SpotifyApi.Builder()
                .setClientId(clientId)
                .setClientSecret(clientSecret)
                .build();
        ClientCredentialsRequest clientCredentialsRequest = spotifyApi.clientCredentials().build();

        ClientCredentials clientCredentials = clientCredentialsRequest.execute();
        spotifyApi.setAccessToken(clientCredentials.getAccessToken());

        String playlistId = "5iZh1symrVbgqWNwXACTZ2";
        GetPlaylistRequest req = spotifyApi.getPlaylist(playlistId)
                .fields("description,owner").build();

        Callable<Playlist> playlistCall = () -> req.execute();

        ExecutorService executor = Executors.newSingleThreadExecutor();

        try {
            executor.submit(playlistCall).get(5, TimeUnit.SECONDS);
        } catch (InterruptedException | TimeoutException | ExecutionException e) {
            fail("Timeout");
        }
    }

**Comment by Selbi182** [comment]
Weird, I've been using this library for a very long time now and never had any issues with 429 errors. They were, as you would expect, properly thrown, including the retry-after field:

```java
try {
  // some SpotifyAPI call
} catch (TooManyRequestsException e) {
  int timeout = e.getRetryAfter();
  Thread.sleep(timeout * 1000); // just as example
  // retry call
}
```

I'm just wondering if I missed something here.
