### ISSUE TITLE
Code Smells Treatment in the Repository

### ISSUE THREAD

**Issue by aSTRonuun** [spotify-web-api-java/spotify-web-api-java#364]
Hello Team

I'm studying code smells and I chose this project to start studying how to contribute to real open source projects

Analyzing the code through some static code tools I found some smells related to code style, lack of good practices and some things related to documentation

I'm opening the issue to say that I will try to investigate and bring good solutions more quickly to help you with the project

**Comment by dargmuesli** [comment]
Thank you for letting us know!
In case there are many changes necessary, I'd like to mention a potential migration to Kotlin code which could lessen some boilerplate. but that needs some evaluation first for sure.

**Comment by aSTRonuun** [comment]
Ok, I'm currently studying Kotlin to work with Android projects, I can use this knowledge to try to refactor some components using this language, of course after an analysis as you know

**Comment by dargmuesli** [comment]
Thank you! :heart: Most importantly the library must still be usable for Java projects. I'm pretty sure Kotlin project's output can be a library that Java projects can import.

**Comment by aSTRonuun** [comment]
Hi, I was taking a look at the project... but I still didn't feel comfortable looking at Kotlin, as I'm still learning and using this problem and PR submissions for a college project, I decided to just focus on the code for the quality part with Java

**Comment by dargmuesli** [comment]
Thank you for the update!

**Comment by dargmuesli** [comment]
Hey @aSTRonuun, do you plan to add the unit test I mentioned in https://github.com/spotify-web-api-java/spotify-web-api-java/pull/379#pullrequestreview-1781674510?
