### ISSUE TITLE
Is the library thread-safe?

### ISSUE THREAD

**Issue by gahisee** [spotify-web-api-java/spotify-web-api-java#366]
I just updated my 'old' program to the latest v8.3.3 from 2.x.x.
My app first makes the get-playlists request in one thread via ExecutorService.
Then, it immediately makes the get-devices request and it takes the exception:
**Connection [Not bound] is still allocated**

If I make the get-devices request when the get-playlists completes, all is fine.

**Comment by dargmuesli** [comment]
Are you using [SpotifyApiThreading's `executeAsync`](https://github.com/spotify-web-api-java/spotify-web-api-java/blob/476ad097036ec71fbf5dd55edc4e5276fb93ce29/src/main/java/se/michaelthelin/spotify/SpotifyApiThreading.java)? Would you share a minimal reproduction code example?

**Comment by dargmuesli** [comment]
Let's reopen this once more information is added.
