### ISSUE TITLE
is_playable is null

### ISSUE THREAD

**Issue by Skillkiller** [spotify-web-api-java/spotify-web-api-java#369]
Hello,
I have found an error which was caused by incorrect documentation from Spotify.
The field ``is_playable`` is always null in the Get Album Tracks query because the API does not return this field. In the written documentation as well as in the example response the field is displayed, but this field is not returned in a correct request.

Steps to reproduce:
1. open https://developer.spotify.com/documentation/web-api/reference/get-an-albums-tracks
2. search for the field ``is_playable`` in the written documentation and in the example response
3. perform a real HTTP request using the GUI (example album id ``3fUl3udC3ZyjuRnRvrDroL``)
4. search the field again

Image step 2:
![grafik](https://github.com/spotify-web-api-java/spotify-web-api-java/assets/18444809/5f9fb2dd-6706-48f5-b129-1bb548b0af0a)

Image step 4:
![grafik](https://github.com/spotify-web-api-java/spotify-web-api-java/assets/18444809/682342fe-d543-4a26-affa-96e58268e59c)

**Comment by dargmuesli** [comment]
What is your change request?

**Comment by dargmuesli** [comment]
Hmm, it's hard to judge whether the written documentation is wrong or the data returned by the API. This repository tries to mirror Spotify's specification (documentation) as closely as possible, so I'd keep it the way it currently is.
There is no actual error popping up for you, right? If the field is just always `null` or so then that's the way it is for now. If there is an actual bug though, we can reopen this issue for sure! Thank you for mentioning the quirk!
