### ISSUE TITLE
Issue Report - TestSimpleExecuteAsync in SpotifyApiThreading

### ISSUE THREAD

**Issue by Shenkeeee** [spotify-web-api-java/spotify-web-api-java#378]
### Discussed in https://github.com/spotify-web-api-java/spotify-web-api-java/discussions/377

<div type='discussions-op-text'>

<sup>Originally posted by **Shenkeeee** December 11, 2023</sup>
Hi,

I'd like to report an issue with the "TestSimpleExecuteAsync" method in the SpotifyApiThreading class. The test, which aims to validate asynchronous execution using CompletableFuture, is currently failing for us. The expected outcome is the completion of CompletableFuture with a non-null result, but the test indicates otherwise. A revision might be requested to ensure the expected functionality of the SpotifyApiThreading class.

Thanks!
Mate

File path: src\main\java\se\michaelthelin\spotify\SpotifyApiThreading.java
/**
 * Test: Testing simple asynchronous execution in the SpotifyApiThreading class.
 * Objective: Verifies that CompletableFuture works correctly in the executeAsync method.
 * Expected result: CompletableFuture completes and the result is not null.
 */
@Test
@DisplayName("Testing simple asynchronous execution in the SpotifyApiThreading class")
public void testSimpleExecuteAsync() {
  Callable<Integer> simpleCallable = () -> 42;

  CompletableFuture<Integer> future = SpotifyApiThreading.executeAsync(simpleCallable);

  assertTrue(future.isDone(), "CompletableFuture has completed.");

  assertNotNull(future.join(), "The result is not null.");
}</div>

**Comment by dargmuesli** [comment]
Let's keep it to a discussion first then
