### ISSUE TITLE
CheckUsersFollowPlaylistRequest is not accurate with current documentation

### ISSUE THREAD

**Issue by Maskowh** [spotify-web-api-java/spotify-web-api-java#396]
### Discussed in https://github.com/spotify-web-api-java/spotify-web-api-java/discussions/395

Update CheckUsersFollowPlaylist requests to match the updated endpoint and tghe actual documentation, removing the usage of the `owner_id` param.

**Comment by dargmuesli** [comment]
Released in v8.4.0, should be available soon.
