### ISSUE TITLE
AuthorizationCodeCredentials#getRefreshToken is null

### ISSUE THREAD

**Issue by TUBEOF** [spotify-web-api-java/spotify-web-api-java#399]
```
AuthorizationCodeCredentials authorizationCodeCredentials = authorizationCodeRefreshRequest.execute();
return authorizationCodeCredentials.getRefreshToken();
```

Returns always null

**Comment by dargmuesli** [comment]
> You can keep using the old refresh token until you get a new one. If you don't get a new one, the old one isn't expired yet. In my opinion, this should be (better) documented.

https://community.spotify.com/t5/Spotify-for-Developers/Get-no-refreshtoken-after-refreshing-an-old-token/td-p/5767548
