### ISSUE TITLE
How to use the refresh_token?

### ISSUE THREAD

**Issue by digitaldesaster** [spotify-web-api-java/spotify-web-api-java#7]
Thank you for this great api, works like a charm. i wonder how to use the refresh_token.

After the first authentication i am saving the refreshtoken in the sharedPreferences. on every start i set the refreshToken and call refreshAccessToken.
api.setRefreshToken(refreshToken);
api.refreshAccessToken();

but this does not  work. i have to reauthenticate via a browser to get a fresh accessToken.

what i am doing wrong?

best regards
Alex

**Comment by shroffrushabh** [comment]
Hey @danieldisu  I am trying to use this library like this,

        Api api = Api.builder()
                .refreshToken(refreshToken)
                .build();

        api.setRefreshToken(refreshToken);
        final SettableFuture<RefreshAccessTokenCredentials> refreshAccessTokenCredentialsFuture =
                api.refreshAccessToken().build().getAsync();

        final SpotifyResponse[] spotifyResponse = {null};

        Futures.addCallback(refreshAccessTokenCredentialsFuture, new FutureCallback<RefreshAccessTokenCredentials>() {
            @Override
            public void onSuccess(RefreshAccessTokenCredentials result) {
                spotifyResponse[0] = new SpotifyResponse(result.getAccessToken(), result.getExpiresIn());
            }

            @Override
            public void onFailure(Throwable throwable) {
                throwable.toString();
            }

        });
but I constantly get a 400
