### ISSUE TITLE
Get User Playlist - missing offset and limit

### ISSUE THREAD

**Issue by digitaldesaster** [spotify-web-api-java/spotify-web-api-java#8]
it would be great to have offset and limit available in the getPlaylistsForUser Method. At the moment there seems to be a fixed limit of 20 playlists.

**Comment by patricktyndall** [comment]
@digitaldesaster I'm still getting a fixed limit for the pages and no URL for next page on v 1.5. Did it work for you?

**Comment by thelinmichael** [comment]
@patricktyndall, this is due to a bug in the Web API tracked [here](https://github.com/spotify/web-api/issues/115).
